name:                pdf-etl-tools
version:             0.4.0.0
github:              "githubuser/pdf-etl-tools"
license:             BSD3
author:              "Mark Tullsen"
maintainer:          "example@example.com"
copyright:           "2020 Galois, Inc."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pdf-etl-tools#readme>

dependencies:
- base >= 4.7 && < 5
- bson
- bson-mapping
- bytestring
- containers
- directory
- filepath
- mongoDB
- mtl
- optparse-applicative
- pipes-mongodb      # 0.1.0.0
- pretty-show
- process
- text
- time
- typed-process
- unliftio
- unix
# - bson-generic (needs earlier version of base, maybe portable??)
# - structured-mongoDB
#   * this needs mongoDB < 2 (and other old stuff!)
# - persistent-mongoDB # 2.9.0
#   * doesn't build
# - mongodb-queue      # 0.4.0.1
#   * need older mongoDB


library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fno-warn-orphans

executables:
  pdf-etl-tool:
    # the main tool for populating db
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -fno-warn-orphans
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pdf-etl-tools

  testing:
    main:                Main.hs
    source-dirs:         app-test
    ghc-options:
    - -Wall
    - -fno-warn-orphans
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pdf-etl-tools

tests:
  pdf-etl-tools-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pdf-etl-tools
